# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Movie Mentor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movie Mentor
  pod 'SwiftLint'
  pod 'Kingfisher', '~> 7.0'

  target 'Movie MentorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Movie MentorUITests' do
    # Pods for testing
  end

end
