name: SwiftLint

on:
   push:
     paths:
       - '.github/workflows/lint.yml'
       - '.lint.yml'
       - '**.swift'

jobs:
   SwiftLint:
     runs-on: self-hosted
     steps:
       - uses: actions/checkout@v1
       - name: GitHub Action for SwiftLint
         uses: norio-nomura/action-swiftlint@master
