# References
# https://github.com/marketplace/actions/github-actions-for-swiftlint
#
# as per Apache 2.0 License, we have put in comments any changes to codefile

name: SwiftLint

# added section for 'push'
on:
  push:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

# changed swift-version from 5.6.1 to 5.7 below
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sinoru/actions-setup-swift@v2
        with:
          swift-version: '5.7'
      - name: GitHub Actions for SwiftLint
        uses: sinoru/actions-swiftlint@v6
# removed steps for other variations of the action
